# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic\AddClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addClient(object):
    def setupUi(self, addClient):
        addClient.setObjectName("addClient")
        addClient.resize(487, 216)
        addClient.setMinimumSize(QtCore.QSize(487, 216))
        addClient.setMaximumSize(QtCore.QSize(487, 216))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addClient.setWindowIcon(icon)
        addClient.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(addClient)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.micrologo11 = QtWidgets.QLabel(addClient)
        self.micrologo11.setMinimumSize(QtCore.QSize(30, 30))
        self.micrologo11.setMaximumSize(QtCore.QSize(30, 30))
        self.micrologo11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micrologo11.setText("")
        self.micrologo11.setPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"))
        self.micrologo11.setAlignment(QtCore.Qt.AlignCenter)
        self.micrologo11.setObjectName("micrologo11")
        self.horizontalLayout_6.addWidget(self.micrologo11)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.addNewClientText = QtWidgets.QLabel(addClient)
        self.addNewClientText.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.addNewClientText.setFont(font)
        self.addNewClientText.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.addNewClientText.setObjectName("addNewClientText")
        self.horizontalLayout_7.addWidget(self.addNewClientText)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.writeNewClient = QtWidgets.QLabel(addClient)
        self.writeNewClient.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.writeNewClient.setFont(font)
        self.writeNewClient.setAlignment(QtCore.Qt.AlignCenter)
        self.writeNewClient.setObjectName("writeNewClient")
        self.verticalLayout_3.addWidget(self.writeNewClient)
        self.nameNewClient = QtWidgets.QLineEdit(addClient)
        self.nameNewClient.setMinimumSize(QtCore.QSize(0, 30))
        self.nameNewClient.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.nameNewClient.setObjectName("nameNewClient")
        self.verticalLayout_3.addWidget(self.nameNewClient)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.error = QtWidgets.QLabel(addClient)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(170, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.horizontalLayout_8.addWidget(self.error)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.acceptButton = QtWidgets.QPushButton(addClient)
        self.acceptButton.setMinimumSize(QtCore.QSize(0, 30))
        self.acceptButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.acceptButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_8.addWidget(self.acceptButton)
        self.rejectButton = QtWidgets.QPushButton(addClient)
        self.rejectButton.setMinimumSize(QtCore.QSize(0, 30))
        self.rejectButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rejectButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout_8.addWidget(self.rejectButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)

        self.retranslateUi(addClient)
        QtCore.QMetaObject.connectSlotsByName(addClient)

    def retranslateUi(self, addClient):
        _translate = QtCore.QCoreApplication.translate
        addClient.setWindowTitle(_translate("addClient", "TransCom - новый клиент"))
        self.addNewClientText.setText(_translate("addClient", "Добавление клиента"))
        self.writeNewClient.setText(_translate("addClient", "Напишите имя нового клиента"))
        self.acceptButton.setText(_translate("addClient", "Подтвердить"))
        self.rejectButton.setText(_translate("addClient", "Отменить"))
