# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic\addTrans.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addTrans(object):
    def setupUi(self, addTrans):
        addTrans.setObjectName("addTrans")
        addTrans.resize(535, 240)
        addTrans.setMinimumSize(QtCore.QSize(535, 240))
        addTrans.setMaximumSize(QtCore.QSize(535, 240))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addTrans.setWindowIcon(icon)
        addTrans.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(addTrans)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.micrologo2 = QtWidgets.QLabel(addTrans)
        self.micrologo2.setMinimumSize(QtCore.QSize(30, 30))
        self.micrologo2.setMaximumSize(QtCore.QSize(30, 30))
        self.micrologo2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micrologo2.setText("")
        self.micrologo2.setPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"))
        self.micrologo2.setAlignment(QtCore.Qt.AlignCenter)
        self.micrologo2.setObjectName("micrologo2")
        self.horizontalLayout_5.addWidget(self.micrologo2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.AddNewTransText = QtWidgets.QLabel(addTrans)
        self.AddNewTransText.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.AddNewTransText.setFont(font)
        self.AddNewTransText.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.AddNewTransText.setObjectName("AddNewTransText")
        self.horizontalLayout_4.addWidget(self.AddNewTransText)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.howModelName = QtWidgets.QLabel(addTrans)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.howModelName.setFont(font)
        self.howModelName.setStyleSheet("")
        self.howModelName.setObjectName("howModelName")
        self.horizontalLayout.addWidget(self.howModelName)
        self.newModelName = QtWidgets.QLineEdit(addTrans)
        self.newModelName.setMinimumSize(QtCore.QSize(0, 30))
        self.newModelName.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.newModelName.setObjectName("newModelName")
        self.horizontalLayout.addWidget(self.newModelName)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.howTonnage = QtWidgets.QLabel(addTrans)
        self.howTonnage.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.howTonnage.setFont(font)
        self.howTonnage.setStyleSheet("")
        self.howTonnage.setObjectName("howTonnage")
        self.horizontalLayout_2.addWidget(self.howTonnage)
        self.newTonnage = QtWidgets.QDoubleSpinBox(addTrans)
        self.newTonnage.setMinimumSize(QtCore.QSize(0, 30))
        self.newTonnage.setStyleSheet("background-color: white;\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"selection-background-color: white; \n"
"selection-color: black")
        self.newTonnage.setObjectName("newTonnage")
        self.horizontalLayout_2.addWidget(self.newTonnage)
        self.tons = QtWidgets.QLabel(addTrans)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.tons.setFont(font)
        self.tons.setObjectName("tons")
        self.horizontalLayout_2.addWidget(self.tons)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gosznakText = QtWidgets.QLabel(addTrans)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.gosznakText.setFont(font)
        self.gosznakText.setStyleSheet("")
        self.gosznakText.setObjectName("gosznakText")
        self.horizontalLayout_3.addWidget(self.gosznakText)
        self.newCarNumber = QtWidgets.QLineEdit(addTrans)
        self.newCarNumber.setMinimumSize(QtCore.QSize(0, 30))
        self.newCarNumber.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.newCarNumber.setObjectName("newCarNumber")
        self.horizontalLayout_3.addWidget(self.newCarNumber)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.error = QtWidgets.QLabel(addTrans)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(170, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.horizontalLayout_7.addWidget(self.error)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.acceptButton = QtWidgets.QPushButton(addTrans)
        self.acceptButton.setMinimumSize(QtCore.QSize(0, 30))
        self.acceptButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.acceptButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout_7.addWidget(self.acceptButton)
        self.rejectButton = QtWidgets.QPushButton(addTrans)
        self.rejectButton.setMinimumSize(QtCore.QSize(0, 30))
        self.rejectButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.rejectButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout_7.addWidget(self.rejectButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)

        self.retranslateUi(addTrans)
        QtCore.QMetaObject.connectSlotsByName(addTrans)

    def retranslateUi(self, addTrans):
        _translate = QtCore.QCoreApplication.translate
        addTrans.setWindowTitle(_translate("addTrans", "TransCom - новый транспорт"))
        self.AddNewTransText.setText(_translate("addTrans", "Добавление нового транспорта"))
        self.howModelName.setText(_translate("addTrans", "Название модели:"))
        self.howTonnage.setText(_translate("addTrans", "Грузоподъёмность модели:"))
        self.tons.setText(_translate("addTrans", "тонн"))
        self.gosznakText.setText(_translate("addTrans", "Введите номерной знак:"))
        self.acceptButton.setText(_translate("addTrans", "Подтвердить"))
        self.rejectButton.setText(_translate("addTrans", "Отменить"))
