# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic\clients.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Clients(object):
    def setupUi(self, Clients):
        Clients.setObjectName("Clients")
        Clients.resize(685, 510)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Clients.setWindowIcon(icon)
        Clients.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Clients)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.clientList = QtWidgets.QLabel(Clients)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clientList.setFont(font)
        self.clientList.setObjectName("clientList")
        self.verticalLayout_2.addWidget(self.clientList)
        self.clientsList = QtWidgets.QListWidget(Clients)
        self.clientsList.setObjectName("clientsList")
        self.verticalLayout_2.addWidget(self.clientsList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addNewClient = QtWidgets.QPushButton(Clients)
        self.addNewClient.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addNewClient.setFont(font)
        self.addNewClient.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color:rgb(85, 170, 0);")
        self.addNewClient.setObjectName("addNewClient")
        self.verticalLayout.addWidget(self.addNewClient)
        self.remClients = QtWidgets.QPushButton(Clients)
        self.remClients.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remClients.setFont(font)
        self.remClients.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color: rgb(255, 0, 0);")
        self.remClients.setObjectName("remClients")
        self.verticalLayout.addWidget(self.remClients)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.micrologo10 = QtWidgets.QLabel(Clients)
        self.micrologo10.setMinimumSize(QtCore.QSize(30, 30))
        self.micrologo10.setMaximumSize(QtCore.QSize(30, 30))
        self.micrologo10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micrologo10.setText("")
        self.micrologo10.setPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"))
        self.micrologo10.setAlignment(QtCore.Qt.AlignCenter)
        self.micrologo10.setObjectName("micrologo10")
        self.horizontalLayout.addWidget(self.micrologo10)
        self.infoAboutCliens = QtWidgets.QLabel(Clients)
        self.infoAboutCliens.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.infoAboutCliens.setFont(font)
        self.infoAboutCliens.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.infoAboutCliens.setObjectName("infoAboutCliens")
        self.horizontalLayout.addWidget(self.infoAboutCliens)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.back_to_main2 = QtWidgets.QPushButton(Clients)
        self.back_to_main2.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_main2.setFont(font)
        self.back_to_main2.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.back_to_main2.setObjectName("back_to_main2")
        self.horizontalLayout.addWidget(self.back_to_main2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(Clients)
        QtCore.QMetaObject.connectSlotsByName(Clients)

    def retranslateUi(self, Clients):
        _translate = QtCore.QCoreApplication.translate
        Clients.setWindowTitle(_translate("Clients", "TransCom - клиенты"))
        self.clientList.setText(_translate("Clients", "Список всех клиентов"))
        self.addNewClient.setText(_translate("Clients", "Добавить нового клиента"))
        self.remClients.setText(_translate("Clients", "Удалить клиента"))
        self.infoAboutCliens.setText(_translate("Clients", "Информация о клиентах"))
        self.back_to_main2.setText(_translate("Clients", "Вернуться в главное меню"))
