# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic\controlTrans.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControlTrans(object):
    def setupUi(self, ControlTrans):
        ControlTrans.setObjectName("ControlTrans")
        ControlTrans.resize(917, 553)
        ControlTrans.setMinimumSize(QtCore.QSize(917, 553))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ControlTrans.setWindowIcon(icon)
        ControlTrans.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ControlTrans)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.micrologo6 = QtWidgets.QLabel(ControlTrans)
        self.micrologo6.setMinimumSize(QtCore.QSize(30, 30))
        self.micrologo6.setMaximumSize(QtCore.QSize(30, 30))
        self.micrologo6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micrologo6.setText("")
        self.micrologo6.setPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"))
        self.micrologo6.setAlignment(QtCore.Qt.AlignCenter)
        self.micrologo6.setObjectName("micrologo6")
        self.horizontalLayout.addWidget(self.micrologo6)
        self.infoAboutTrans = QtWidgets.QLabel(ControlTrans)
        self.infoAboutTrans.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.infoAboutTrans.setFont(font)
        self.infoAboutTrans.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.infoAboutTrans.setObjectName("infoAboutTrans")
        self.horizontalLayout.addWidget(self.infoAboutTrans)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.back_to_main1 = QtWidgets.QPushButton(ControlTrans)
        self.back_to_main1.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_main1.setFont(font)
        self.back_to_main1.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.back_to_main1.setObjectName("back_to_main1")
        self.horizontalLayout.addWidget(self.back_to_main1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.transList = QtWidgets.QLabel(ControlTrans)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.transList.setFont(font)
        self.transList.setObjectName("transList")
        self.verticalLayout_2.addWidget(self.transList)
        self.allTransList = QtWidgets.QTableWidget(ControlTrans)
        self.allTransList.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.allTransList.setShowGrid(True)
        self.allTransList.setGridStyle(QtCore.Qt.SolidLine)
        self.allTransList.setObjectName("allTransList")
        self.allTransList.setColumnCount(4)
        self.allTransList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allTransList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTransList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTransList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allTransList.setHorizontalHeaderItem(3, item)
        self.allTransList.horizontalHeader().setCascadingSectionResizes(False)
        self.allTransList.horizontalHeader().setDefaultSectionSize(150)
        self.allTransList.horizontalHeader().setSortIndicatorShown(False)
        self.allTransList.horizontalHeader().setStretchLastSection(True)
        self.allTransList.verticalHeader().setCascadingSectionResizes(False)
        self.allTransList.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.allTransList)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addNewTrans = QtWidgets.QPushButton(ControlTrans)
        self.addNewTrans.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addNewTrans.setFont(font)
        self.addNewTrans.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color:rgb(85, 170, 0);")
        self.addNewTrans.setObjectName("addNewTrans")
        self.verticalLayout.addWidget(self.addNewTrans)
        self.remOldTrans = QtWidgets.QPushButton(ControlTrans)
        self.remOldTrans.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.remOldTrans.setFont(font)
        self.remOldTrans.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"color: rgb(255, 0, 0);")
        self.remOldTrans.setObjectName("remOldTrans")
        self.verticalLayout.addWidget(self.remOldTrans)
        self.redactOldTrans = QtWidgets.QPushButton(ControlTrans)
        self.redactOldTrans.setMinimumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.redactOldTrans.setFont(font)
        self.redactOldTrans.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.redactOldTrans.setObjectName("redactOldTrans")
        self.verticalLayout.addWidget(self.redactOldTrans)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ControlTrans)
        QtCore.QMetaObject.connectSlotsByName(ControlTrans)

    def retranslateUi(self, ControlTrans):
        _translate = QtCore.QCoreApplication.translate
        ControlTrans.setWindowTitle(_translate("ControlTrans", "TransCom - транспорт"))
        self.infoAboutTrans.setText(_translate("ControlTrans", "Информация о транспорте"))
        self.back_to_main1.setText(_translate("ControlTrans", "Вернуться в главное меню"))
        self.transList.setText(_translate("ControlTrans", "Список всех транспортных средств"))
        item = self.allTransList.horizontalHeaderItem(0)
        item.setText(_translate("ControlTrans", "Модель"))
        item = self.allTransList.horizontalHeaderItem(1)
        item.setText(_translate("ControlTrans", "Грузоподъемность (т.)"))
        item = self.allTransList.horizontalHeaderItem(2)
        item.setText(_translate("ControlTrans", "Номерной знак"))
        item = self.allTransList.horizontalHeaderItem(3)
        item.setText(_translate("ControlTrans", "В пути?"))
        self.addNewTrans.setText(_translate("ControlTrans", "Добавить новый транспорт"))
        self.remOldTrans.setText(_translate("ControlTrans", "Удалить транспорт"))
        self.redactOldTrans.setText(_translate("ControlTrans", "Изменить информацию о транспорте"))
