# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ic\newOrder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewOrder(object):
    def setupUi(self, NewOrder):
        NewOrder.setObjectName("NewOrder")
        NewOrder.resize(715, 300)
        NewOrder.setMinimumSize(QtCore.QSize(715, 300))
        NewOrder.setMaximumSize(QtCore.QSize(715, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NewOrder.setWindowIcon(icon)
        NewOrder.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(NewOrder)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.micrologo9 = QtWidgets.QLabel(NewOrder)
        self.micrologo9.setMinimumSize(QtCore.QSize(30, 30))
        self.micrologo9.setMaximumSize(QtCore.QSize(30, 30))
        self.micrologo9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.micrologo9.setText("")
        self.micrologo9.setPixmap(QtGui.QPixmap("ic\\../pic/micrologo.png"))
        self.micrologo9.setAlignment(QtCore.Qt.AlignCenter)
        self.micrologo9.setObjectName("micrologo9")
        self.horizontalLayout_7.addWidget(self.micrologo9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.addNewOrder = QtWidgets.QLabel(NewOrder)
        self.addNewOrder.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.addNewOrder.setFont(font)
        self.addNewOrder.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.addNewOrder.setObjectName("addNewOrder")
        self.horizontalLayout_8.addWidget(self.addNewOrder)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem2)
        self.chooseClient = QtWidgets.QLabel(NewOrder)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chooseClient.setFont(font)
        self.chooseClient.setObjectName("chooseClient")
        self.horizontalLayout_9.addWidget(self.chooseClient)
        self.choosedClient = QtWidgets.QComboBox(NewOrder)
        self.choosedClient.setMinimumSize(QtCore.QSize(200, 25))
        self.choosedClient.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.choosedClient.setObjectName("choosedClient")
        self.horizontalLayout_9.addWidget(self.choosedClient)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.chooseCity = QtWidgets.QLabel(NewOrder)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.chooseCity.setFont(font)
        self.chooseCity.setObjectName("chooseCity")
        self.horizontalLayout_10.addWidget(self.chooseCity)
        self.choosedCity = QtWidgets.QComboBox(NewOrder)
        self.choosedCity.setMinimumSize(QtCore.QSize(200, 25))
        self.choosedCity.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.choosedCity.setObjectName("choosedCity")
        self.horizontalLayout_10.addWidget(self.choosedCity)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem6)
        self.ChooseWeight = QtWidgets.QLabel(NewOrder)
        self.ChooseWeight.setMinimumSize(QtCore.QSize(0, 30))
        self.ChooseWeight.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.ChooseWeight.setFont(font)
        self.ChooseWeight.setStyleSheet("")
        self.ChooseWeight.setObjectName("ChooseWeight")
        self.horizontalLayout_11.addWidget(self.ChooseWeight)
        self.orderTonnage = QtWidgets.QDoubleSpinBox(NewOrder)
        self.orderTonnage.setMinimumSize(QtCore.QSize(100, 20))
        self.orderTonnage.setMaximumSize(QtCore.QSize(16777215, 30))
        self.orderTonnage.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;\n"
"HighlightedText: white;\n"
"selection-background-color: white; \n"
"selection-color:black")
        self.orderTonnage.setObjectName("orderTonnage")
        self.horizontalLayout_11.addWidget(self.orderTonnage)
        self.tonsOrder = QtWidgets.QLabel(NewOrder)
        self.tonsOrder.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tonsOrder.setFont(font)
        self.tonsOrder.setObjectName("tonsOrder")
        self.horizontalLayout_11.addWidget(self.tonsOrder)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.chooseTrans = QtWidgets.QLabel(NewOrder)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.chooseTrans.setFont(font)
        self.chooseTrans.setObjectName("chooseTrans")
        self.horizontalLayout_12.addWidget(self.chooseTrans)
        self.choosedTrans = QtWidgets.QComboBox(NewOrder)
        self.choosedTrans.setMinimumSize(QtCore.QSize(400, 25))
        self.choosedTrans.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.choosedTrans.setObjectName("choosedTrans")
        self.horizontalLayout_12.addWidget(self.choosedTrans)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.error = QtWidgets.QLabel(NewOrder)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.error.setFont(font)
        self.error.setStyleSheet("color: rgb(170, 0, 0);")
        self.error.setText("")
        self.error.setObjectName("error")
        self.horizontalLayout.addWidget(self.error)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.acceptButton = QtWidgets.QPushButton(NewOrder)
        self.acceptButton.setMinimumSize(QtCore.QSize(0, 30))
        self.acceptButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.acceptButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.acceptButton.setObjectName("acceptButton")
        self.horizontalLayout.addWidget(self.acceptButton)
        self.rejectButton = QtWidgets.QPushButton(NewOrder)
        self.rejectButton.setMinimumSize(QtCore.QSize(0, 30))
        self.rejectButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.rejectButton.setStyleSheet("background-color: \'white\';\n"
"border-radius: 5px;\n"
"border-style: solid;\n"
"border-width: 2px;\n"
"border-color: black;")
        self.rejectButton.setObjectName("rejectButton")
        self.horizontalLayout.addWidget(self.rejectButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NewOrder)
        QtCore.QMetaObject.connectSlotsByName(NewOrder)

    def retranslateUi(self, NewOrder):
        _translate = QtCore.QCoreApplication.translate
        NewOrder.setWindowTitle(_translate("NewOrder", "TransCom - новый заказ"))
        self.addNewOrder.setText(_translate("NewOrder", "-- Новый заказ --"))
        self.chooseClient.setText(_translate("NewOrder", "Выберите клиента:"))
        self.chooseCity.setText(_translate("NewOrder", "Выберите город:"))
        self.ChooseWeight.setText(_translate("NewOrder", "Укажите вес груза:"))
        self.tonsOrder.setText(_translate("NewOrder", "тонн"))
        self.chooseTrans.setText(_translate("NewOrder", "Выберите транспорт:"))
        self.acceptButton.setText(_translate("NewOrder", "Подтвердить"))
        self.rejectButton.setText(_translate("NewOrder", "Отменить"))
